// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrS-TV1becknKBBZcoAD1dRTnLrNSgn8',
    appId: '1:834645077487:web:1d59fd6f8134ecfd861a1a',
    messagingSenderId: '834645077487',
    projectId: 'labwork-3f051',
    authDomain: 'labwork-3f051.firebaseapp.com',
    storageBucket: 'labwork-3f051.appspot.com',
    measurementId: 'G-B3D026FJK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgohybzRf8dWrngE3166GXYotboxBRrE',
    appId: '1:834645077487:android:6fafc5c418f5e851861a1a',
    messagingSenderId: '834645077487',
    projectId: 'labwork-3f051',
    storageBucket: 'labwork-3f051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRM0vxo_STxNM_rfMwp5ZBNC3-BAT2K34',
    appId: '1:834645077487:ios:e622bbe882b0bcaa861a1a',
    messagingSenderId: '834645077487',
    projectId: 'labwork-3f051',
    storageBucket: 'labwork-3f051.appspot.com',
    iosClientId: '834645077487-j5v77pqsn4iov0g1ev51jukuknkr84he.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
